name: Deploy SQL Scripts to SQL Server

on:
  push:
    branches:
      - main

jobs:
  deploy-sql:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sqlcmd on macOS
        run: |
          brew update
          arch -arm64 brew install msodbcsql18 mssql-tools18
          brew link mssql-tools18

      - name: Run SQL Script
        run: |
          /opt/homebrew/bin/sqlcmd -S ${{ secrets.DB_SERVER }} -d ${{ secrets.DB_NAME }} -U ${{ secrets.DB_USERNAME }} -P ${{ secrets.DB_PASSWORD }} -i sql/001_create_tables.sql
